# Generated by Django 5.0.6 on 2024-06-18 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(default='', max_length=100)),
                ('beskrivelse', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('bilde', models.ImageField(upload_to='uploads/')),
                ('dato', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('passord', models.CharField(max_length=100)),
            ],
        ),
    ]
