# Generated by Django 5.0.6 on 2024-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bredde',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='post',
            name='lengde',
            field=models.IntegerField(default=500),
        ),
    ]
