# Generated by Django 5.0.6 on 2024-06-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_bredde_post_lengde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bredde',
            new_name='høyde',
        ),
    ]
