# Generated by Django 5.0.6 on 2024-06-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_bredde_post_høyde'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
