# Generated by Django 5.0.6 on 2024-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='høyde_showcase',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='lengde_showcase',
            field=models.IntegerField(default=1000),
        ),
    ]
