# Generated by Django 5.0.6 on 2024-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='Navn', max_length=50)),
                ('melding', models.CharField(default='Melding', max_length=2500)),
            ],
        ),
    ]
