# Generated by Django 5.0.6 on 2024-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_kontakt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='melding',
            field=models.TextField(default='Melding', max_length=2500),
        ),
    ]
