# Generated by Django 5.0.6 on 2024-06-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_kontakt_melding'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='høyde_showcase_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lengde_showcase_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='høyde_showcase',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lengde_showcase',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
