# Generated by Django 5.0.6 on 2024-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_post_høyde_showcase_auto_post_lengde_showcase_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='høyde_showcase_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='lengde_showcase_auto',
            field=models.BooleanField(default=False),
        ),
    ]
