# Generated by Django 5.0.6 on 2024-06-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_post_høyde_showcase_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='høyde',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='lengde',
            field=models.IntegerField(default=50),
        ),
    ]
