# Generated by Django 5.0.6 on 2024-07-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_post_portrett_eller_horizontal'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='email',
            field=models.CharField(default='Email', max_length=70),
        ),
    ]
